# lists, arrays and dictionaries :D

In [1]:
import numpy as np

In [2]:
listpokemon_names = ['psyduck', 'eevee', 'magikarp']
listpokemon_real = ['duck', 'fox', 'fish']  # these are lists

arraypokemon_names = np.array(['psyduck', 'eevee', 'magikarp'])
# and these are numpy arrays
arraypokemon_real = np.array(['duck', 'fox', 'fish'])

pokemon_info = {
    'psyduck': 'duck',
    'eevee': 'fox',
    'magikarp': 'fish'
}  # and this is a dictionary. remember the commas.

In [3]:
#first thing in the list/array/dictionary is index 0

#tis how you access things in list
print(listpokemon_names[0]) 
print(listpokemon_real[-1]) #negative indexing is a thing too. no need to know list size :D

psyduck
fish


### added negative indexing

In [4]:
#negative indexing. 0 is the 'first' one, -1 is the 'last' one, -2 is 'second last'
print(listpokemon_real[0])
print(listpokemon_real[-1])
print(listpokemon_real[-2])
print(listpokemon_real[-5]) #can't go over the list range even when negative indexing lol

duck
fish
fox


IndexError: list index out of range

In [5]:
#tis how you access things in dictionaries
pokemon_info['eevee'] #get value (fox) for key (eevee)

print(pokemon_info.keys()) #get all keys
print(pokemon_info.values()) #get all values. basically the socalled definition

dict_keys(['psyduck', 'eevee', 'magikarp'])
dict_values(['duck', 'fox', 'fish'])


In [6]:
py_pokemoninfo = [['psyduck', 'duck'], ['eevee', 'fox'], ['magikarp', 'fish']] #store a list in a list (an array)

In [7]:
print(py_pokemoninfo[1])
#can index as normal :D

['eevee', 'fox']


# list vs array
lists can have multiple variable types. arrays can only have 1

In [8]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

np_array_2d = np.array(py_list_2d)      # Reusing the Python list 
                                        # to create a NEW
                                        # NumPy array
print('list length is', len(py_list_2d))
print('array length is', len (np_array_2d))
print('array shape is', np_array_2d.shape)

list length is 10
array length is 10
array shape is (10, 2)


In [9]:
pylist = [1,2,3,4,5]
nparray = np.array(pylist)

print(nparray + 10) #this works
print(pylist + 10) #but this doesnt

[11 12 13 14 15]


TypeError: can only concatenate list (not "int") to list

### added more print statements to show what stuff do

In [10]:
pylist1 = [1,2,3,4,5]
pylist2 = [10,20,30,40,50]

array1 = np.array(pylist1)
array2 = np.array(pylist2)

print(pylist1 + pylist2) #the list grows
print(array1 + array2) #the values in the array get added
print('\n')

#multiplying a list makes x more of the values in the list
#multiplying an array multiplies each value by x
multiplylst = pylist1 * 3
print(multiplylst)
print('\n')

#can't square a list, but can square an array
squared_array = array1** 2
rooted_array = array1 ** 0.5
print(squared_array)
print(rooted_array)
print('\n')

#can't ask questions to a list, but can to an array
#pylist1 > 3 this doesnt work an error occurs
array1 > 3

#can use base python math functions on both
#but can't use the dots on list, can for arrays
print(array1.sum())

[1, 2, 3, 4, 5, 10, 20, 30, 40, 50]
[11 22 33 44 55]


[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


[ 1  4  9 16 25]
[1.         1.41421356 1.73205081 2.         2.23606798]


15
